name: Build on macOS
on: [push]

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Build
        run: clang -E test.c
      - name: python test
        run: python3 open-test.py
